export type SampleEvent = {
  citySlug: string;
  venueName: string;
  title: string;
  artists: string[];
  daysFromNow: number;
  hour?: number;
  ticketUrl: string;
  priceMin: number;
  priceMax: number;
};

/** Demo koncerty — daty liczone względem dnia seeda. ticketUrl kończy się na /example. */
export const SAMPLE_EVENTS: SampleEvent[] = [
  // Warszawa — małe kluby
  {
    citySlug: "warszawa",
    venueName: "Chmury",
    title: "Obscura + Fractal Universe",
    artists: ["Obscura", "Fractal Universe"],
    daysFromNow: 0,
    hour: 20,
    ticketUrl: "https://www.ebilet.pl/example",
    priceMin: 60,
    priceMax: 90,
  },
  {
    citySlug: "warszawa",
    venueName: "Proxima",
    title: "Decapitated + support",
    artists: ["Decapitated"],
    daysFromNow: 2,
    ticketUrl: "https://goingapp.pl/example",
    priceMin: 80,
    priceMax: 120,
  },
  {
    citySlug: "warszawa",
    venueName: "Hydrozagadka",
    title: "Mgła — Age of Reason Tour",
    artists: ["Mgła"],
    daysFromNow: 5,
    ticketUrl: "https://www.eventim.pl/example",
    priceMin: 70,
    priceMax: 100,
  },
  {
    citySlug: "warszawa",
    venueName: "Pogo",
    title: "Thy Disease + Hate",
    artists: ["Thy Disease", "Hate"],
    daysFromNow: 9,
    ticketUrl: "https://goingapp.pl/example",
    priceMin: 50,
    priceMax: 80,
  },
  {
    citySlug: "warszawa",
    venueName: "Stodoła",
    title: "Behemoth — European Tour 2026",
    artists: ["Behemoth"],
    daysFromNow: 14,
    ticketUrl: "https://www.ebilet.pl/example",
    priceMin: 150,
    priceMax: 350,
  },
  // Kraków
  {
    citySlug: "krakow",
    venueName: "Alchemia",
    title: "Rivers of Nihil — studio live",
    artists: ["Rivers of Nihil"],
    daysFromNow: 1,
    ticketUrl: "https://www.ebilet.pl/example",
    priceMin: 55,
    priceMax: 85,
  },
  {
    citySlug: "krakow",
    venueName: "Strefa",
    title: "Batushka — liturgia koncertowa",
    artists: ["Batushka"],
    daysFromNow: 4,
    ticketUrl: "https://goingapp.pl/example",
    priceMin: 70,
    priceMax: 110,
  },
  {
    citySlug: "krakow",
    venueName: "Kwadrat",
    title: "Meshuggah — Live in Kraków",
    artists: ["Meshuggah"],
    daysFromNow: 12,
    ticketUrl: "https://www.eventim.pl/example",
    priceMin: 180,
    priceMax: 400,
  },
  // Wrocław
  {
    citySlug: "wroclaw",
    venueName: "Vertigo",
    title: "Imperial Triumphant",
    artists: ["Imperial Triumphant"],
    daysFromNow: 0,
    hour: 21,
    ticketUrl: "https://goingapp.pl/example",
    priceMin: 45,
    priceMax: 75,
  },
  {
    citySlug: "wroclaw",
    venueName: "Odra-Fange",
    title: "Dagoba + Betraying the Martyrs",
    artists: ["Dagoba", "Betraying the Martyrs"],
    daysFromNow: 3,
    ticketUrl: "https://www.ebilet.pl/example",
    priceMin: 55,
    priceMax: 90,
  },
  {
    citySlug: "wroclaw",
    venueName: "Tęcza",
    title: "Gojira — Fortitude Tour",
    artists: ["Gojira"],
    daysFromNow: 18,
    ticketUrl: "https://www.ebilet.pl/example",
    priceMin: 140,
    priceMax: 280,
  },
  // Poznań
  {
    citySlug: "poznan",
    venueName: "U Bazyla",
    title: "Amon Amarth — Beserker Tour",
    artists: ["Amon Amarth"],
    daysFromNow: 6,
    ticketUrl: "https://goingapp.pl/example",
    priceMin: 100,
    priceMax: 200,
  },
  {
    citySlug: "poznan",
    venueName: "Meskalina",
    title: "Crystal Viper + Dool",
    artists: ["Crystal Viper", "Dool"],
    daysFromNow: 2,
    ticketUrl: "https://www.eventim.pl/example",
    priceMin: 40,
    priceMax: 65,
  },
  // Gdańsk
  {
    citySlug: "gdansk",
    venueName: "B90",
    title: "Vader — 40 Years of Blasphemy",
    artists: ["Vader"],
    daysFromNow: 7,
    ticketUrl: "https://www.ebilet.pl/example",
    priceMin: 80,
    priceMax: 130,
  },
  {
    citySlug: "gdansk",
    venueName: "Parapet",
    title: "Belzebong + Weedpecker",
    artists: ["Belzebong", "Weedpecker"],
    daysFromNow: 1,
    ticketUrl: "https://goingapp.pl/example",
    priceMin: 35,
    priceMax: 55,
  },
  // Katowice
  {
    citySlug: "katowice",
    venueName: "MegaClub",
    title: "Acid Drinkers — 35 lat",
    artists: ["Acid Drinkers"],
    daysFromNow: 3,
    ticketUrl: "https://www.eventim.pl/example",
    priceMin: 60,
    priceMax: 95,
  },
  {
    citySlug: "katowice",
    venueName: "Królestwo",
    title: "Stillborn + Deivos",
    artists: ["Stillborn", "Deivos"],
    daysFromNow: 10,
    ticketUrl: "https://goingapp.pl/example",
    priceMin: 40,
    priceMax: 70,
  },
  // Łódź
  {
    citySlug: "lodz",
    venueName: "Diesel",
    title: "Trauma + Lux Occulta",
    artists: ["Trauma", "Lux Occulta"],
    daysFromNow: 4,
    ticketUrl: "https://www.ebilet.pl/example",
    priceMin: 45,
    priceMax: 75,
  },
  {
    citySlug: "lodz",
    venueName: "Wytwórnia",
    title: "Septicflesh — Modern Primitive",
    artists: ["Septicflesh"],
    daysFromNow: 15,
    ticketUrl: "https://www.eventim.pl/example",
    priceMin: 90,
    priceMax: 160,
  },
  // Lublin, Szczecin, Bydgoszcz, Białystok, Rzeszów
  {
    citySlug: "lublin",
    venueName: "Graffiti",
    title: "Hellripper + Bütcher",
    artists: ["Hellripper", "Bütcher"],
    daysFromNow: 5,
    ticketUrl: "https://goingapp.pl/example",
    priceMin: 50,
    priceMax: 80,
  },
  {
    citySlug: "szczecin",
    venueName: "Alter Ego",
    title: "Toxic Holocaust",
    artists: ["Toxic Holocaust"],
    daysFromNow: 2,
    ticketUrl: "https://www.ebilet.pl/example",
    priceMin: 55,
    priceMax: 85,
  },
  {
    citySlug: "bydgoszcz",
    venueName: "Mózg",
    title: "Sólstafir — ambient metal night",
    artists: ["Sólstafir"],
    daysFromNow: 8,
    ticketUrl: "https://goingapp.pl/example",
    priceMin: 60,
    priceMax: 90,
  },
  {
    citySlug: "bialystok",
    venueName: "K2",
    title: "Christ Agony + Pandemonium",
    artists: ["Christ Agony", "Pandemonium"],
    daysFromNow: 6,
    ticketUrl: "https://www.eventim.pl/example",
    priceMin: 40,
    priceMax: 65,
  },
  {
    citySlug: "rzeszow",
    venueName: "Strefa Kultury",
    title: "Gaerea + Inferi",
    artists: ["Gaerea", "Inferi"],
    daysFromNow: 11,
    ticketUrl: "https://www.ebilet.pl/example",
    priceMin: 45,
    priceMax: 70,
  },
];
